### PR TITLE
Simplify support and enhanced UI

### PR DESCRIPTION
**Pull request by TCX0Lt0X**
The geometry node tree now respects Simplify settings in Render settings, and supports different subdivision levels for Viewport and Renders. UI for the modifier has been polished for better user usability.

### CODE REVIEW

**Comment by RanmanEmpire** [comment]
Thank you!
Very nice fix!

image

What version of Blender did you make this file with?
For the sake of the users, I'd like to see it made with version 4.0 if possible, but I'm not sure.

 push the UI to deep to operate.
thank you.

**Comment by TCX0Lt0X** [comment]
I used 4.2, specifically 4.2.1 candidate branch. I believe the nodes for the subdivision levels should work down to 4.0, though the Menu Switch node for the UI changes was implemented in 4.1

**Comment by TCX0Lt0X** [comment]
I added in a 4.0 compatible node group, and added a simplify override setting and fixed one link to subdivision levels not routing through the simplify check settings

**Comment by RanmanEmpire** [comment]
Thanks for the very nice update.

I will update the documentation after I merge this in.
At that time I will add your name to the update, would you like me to include a link to your social networking site or something?

**Comment by TCX0Lt0X** [comment]
Na I am good, just happy to contribute.

**Comment by RanmanEmpire** [comment]
Is "Override Simplify Subdivision Limit" working?

**Comment by TCX0Lt0X** [comment]
It appears to be working on my end yes.

**Pull request merged**
